# Generated by Django 4.2.4 on 2023-08-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=100)),
                ('ship_date', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('item_type_dict', models.CharField(max_length=100)),
                ('item_subtype_dict', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=10)),
                ('confirmed', models.CharField(max_length=10)),
                ('archived', models.CharField(max_length=10)),
            ],
        ),
    ]
