# Generated by Django 4.2.4 on 2023-08-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_backorder_order_backorder_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
