# Generated by Django 4.2.4 on 2023-08-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='packages',
            new_name='packages_dict',
        ),
    ]
