# Generated by Django 4.2.4 on 2023-08-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='notes_dict',
            field=models.JSONField(default=dict),
        ),
    ]
