# Generated by Django 4.2.4 on 2023-08-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_order_packages_dict_order_packages_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes_dict',
        ),
        migrations.AddField(
            model_name='order',
            name='notes_array',
            field=models.JSONField(default=list),
        ),
    ]
