# Generated by Django 4.2.4 on 2023-08-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_order_notes_dict_order_notes_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delay',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
