# Generated by Django 4.2.4 on 2023-10-08 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_orderreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreport',
            name='created_date',
        ),
    ]
