# Generated by Django 4.2.4 on 2023-10-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_orderreport_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='backorder_number',
            field=models.IntegerField(default=0),
        ),
    ]
