# Generated by Django 4.2.4 on 2023-10-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_order_backorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.BooleanField(default=False),
        ),
    ]
