# Generated by Django 4.2.4 on 2023-10-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_dimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='index_position',
        ),
        migrations.AddField(
            model_name='dimension',
            name='height',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='dimension',
            name='length',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='dimension',
            name='width',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='package_size',
            field=models.CharField(default='0 x 0 x 0', max_length=50),
        ),
    ]
