# Generated by Django 4.2.4 on 2023-10-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_dimension_height_alter_dimension_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='width',
            field=models.IntegerField(),
        ),
    ]
