# Generated by Django 4.2.4 on 2023-10-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_order_ship_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delay_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
