# Generated by Django 4.2.4 on 2023-10-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_dimension_height_alter_dimension_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_type_dict_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
