# Generated by Django 4.2.4 on 2023-11-15 01:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["item_name"], "verbose_name_plural": "Products"},
        ),
    ]
