# Generated by Django 4.2.4 on 2023-11-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0040_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="item_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
