# Generated by Django 5.0 on 2023-12-07 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_product_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimension',
            options={'ordering': ['length', 'width', 'height'], 'verbose_name_plural': 'Dimensions'},
        ),
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together={('length', 'width', 'height', 'package_size')},
        ),
    ]
