# Generated by Django 5.0 on 2023-12-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_order_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='minimized_status',
        ),
    ]
