# Generated by Django 5.0 on 2024-01-09 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_order_minimized_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderReport',
        ),
    ]
