# Generated by Django 5.0 on 2024-01-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_delete_orderreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_type_dict_hash',
            new_name='item_array_hash',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_subtype_dict',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_type_dict',
        ),
        migrations.AddField(
            model_name='order',
            name='item_array',
            field=models.JSONField(default=list),
        ),
    ]
