# Generated by Django 5.0 on 2024-01-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_lastupdate_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastupdate',
            name='last_updated',
            field=models.CharField(max_length=100),
        ),
    ]
