# Generated by Django 5.0 on 2024-01-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_lastupdate_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastupdate',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
