# Generated by Django 5.0 on 2024-01-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_lastupdate_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delay_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
