# Generated by Django 5.0 on 2024-01-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_order_delay_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='backorder',
        ),
    ]
