# Generated by Django 5.0 on 2024-01-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_order_backorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastupdate',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
