# Generated by Django 5.0 on 2024-01-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_lastupdate_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, default='none', max_length=100),
        ),
    ]
