# Generated by Django 4.2.4 on 2023-08-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_archived_alter_order_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_subtype_dict',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_type_dict',
            field=models.JSONField(default=dict),
        ),
    ]
