# Generated by Django 4.2.4 on 2023-08-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_order_notes_order_notes_dict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
    ]
