# Generated by Django 4.2.4 on 2023-08-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_confirmed_order_ready_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='packages_dict',
        ),
        migrations.AddField(
            model_name='order',
            name='packages_array',
            field=models.JSONField(default=list),
        ),
    ]
