# Generated by Django 4.2.4 on 2023-09-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_order_delay_order_delay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes_array',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='packages_array',
            field=models.JSONField(default=list, null=True),
        ),
    ]
