# Generated by Django 4.2.4 on 2023-09-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_closedorders_openorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedOrders',
        ),
        migrations.DeleteModel(
            name='OpenOrders',
        ),
    ]
