# Generated by Django 4.2.4 on 2023-10-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_minimized_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('submitted_date', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Order Reports',
            },
        ),
    ]
