# Generated by Django 4.2.4 on 2023-10-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_order_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='minimized_status',
            field=models.BooleanField(default=True),
        ),
    ]
