# Generated by Django 4.2.4 on 2023-10-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_order_minimized_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_position', models.IntegerField(default=0)),
                ('package_size', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Dimensions',
            },
        ),
    ]
