# Generated by Django 4.2.4 on 2023-10-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_order_delay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delay_tbd',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
