# Generated by Django 4.1.1 on 2022-10-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=10)),
                ('customer', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=255)),
                ('weight_and_dimensions', models.TextField(max_length=255)),
                ('confirmed_ready_date', models.CharField(max_length=100)),
                ('pickup_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OpenOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=10)),
                ('customer', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=255)),
                ('weight_and_dimensions', models.TextField(max_length=255)),
                ('confirmed_ready_date', models.CharField(max_length=100)),
                ('pickup_status', models.CharField(max_length=10)),
            ],
        ),
    ]
