# Generated by Django 4.1.1 on 2022-10-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedorders',
            name='confirmed_ready_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='closedorders',
            name='pickup_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='closedorders',
            name='weight_and_dimensions',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='openorders',
            name='confirmed_ready_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='openorders',
            name='pickup_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='openorders',
            name='weight_and_dimensions',
            field=models.TextField(default='', max_length=255),
        ),
    ]
