# Generated by Django 4.1.1 on 2022-10-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_closedorders_confirmed_ready_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenOrders',
            new_name='Orders',
        ),
        migrations.DeleteModel(
            name='ClosedOrders',
        ),
    ]
