# Generated by Django 4.1.1 on 2022-10-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_openorders_orders_delete_closedorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pickup_status',
            new_name='pickup_up',
        ),
    ]
