# Generated by Django 4.1.1 on 2022-10-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_orders_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pickup_up',
            new_name='picked_up',
        ),
    ]
