# Generated by Django 4.1.1 on 2022-10-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_pickup_up_order_picked_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmed_ready_date',
            field=models.DateField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
